name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Dockerhub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  

    - name: Get the Current Date
      id: date
      run: echo date=$(date +'%Y-%m-%d--%M-%S') >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./dockerfiles/jupyterlab/
        file: ./dockerfiles/jupyterlab/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USER}}/jupyterlab
        labels: ${{ steps.date.outputs.date }}
